spring.application.name=ZipMart

spring.database.url=jdbc:mysql://localhost:3306/ZipMart
spring.database.username=root
spring.database.password=Nikhil

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect